kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootcamp-app
  labels:
    app: bootcamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcamp-app
  template:
    metadata:
      labels:
        app: bootcamp-app
    spec:
      containers:
        - name: bootcamp-app
          image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/putrifradila-dev/dila:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: DB_NAME