kind: Service
apiVersion: v1
metadata:
  name: bootcamp-app
  labels:
    app: bootcamp-app
spec:
  selector:
    app: bootcamp-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000